load("@obazl_tools_cc//config/cc:CONFIG.bzl",
     _BASE_COPTS    = "BASE_COPTS",
     _BASE_LINKOPTS = "BASE_LINKOPTS",
     _BASE_LOCAL_DEFINES = "BASE_LOCAL_DEFINES")

BASE_SRCS          = []
BASE_DEPS          = []
BASE_INCLUDE_PATHS = []
BASE_COPTS         = _BASE_COPTS
BASE_LINKOPTS      = _BASE_LINKOPTS
BASE_LOCAL_DEFINES = _BASE_LOCAL_DEFINES
BASE_DEFINES       = []
