(display "loading //convert/scm:convert.scm")
(newline)

(define (dune-pkg->bazel-pkg dir)
  (display "dune-pkg->bazel-pkg") (newline)
  (display dir) (newline)
  (for-each (lambda (dirent)
              (if (directory? dirent)
                  (if (and (not (equal? "." dirent))
                           (not (equal? ".." dirent)))
                      (dune-pkg->bazel-pkg dirent))))
            (directory->list dir))
  )

(define (obazl-convert f)
  (display (string-append "running default convert handler proc: " f))
  (newline)
  (for-each (lambda (dirent)
              (if (directory? dirent)
                  (if (and (not (equal? "." dirent))
                            (not (equal? ".." dirent)))
                      (dune-pkg->bazel-pkg dirent))))
            (directory->list "."))
    (newline)
  )

