#include "log.h"
#include "token_debug.h"

const char *token_name[256] = {
[TK_ALIAS] = "TK_ALIAS",
[TK_AMP] = "TK_AMP",
[TK_AMP_EQ] = "TK_AMP_EQ",
[TK_AND] = "TK_AND",
[TK_ARROW] = "TK_ARROW",
[TK_AS] = "TK_AS",
[TK_ASSERT] = "TK_ASSERT",
[TK_BANG] = "TK_BANG",
[TK_BANG_EQ] = "TK_BANG_EQ",
[TK_BDQ] = "TK_BDQ",
[TK_BDQ3] = "TK_BDQ3",
[TK_BREAK] = "TK_BREAK",
[TK_BSQ] = "TK_BSQ",
[TK_BSQ3] = "TK_BSQ3",
[TK_CARET] = "TK_CARET",
[TK_CARET_EQ] = "TK_CARET_EQ",
[TK_CLASS] = "TK_CLASS",
[TK_COLON] = "TK_COLON",
[TK_COMMA] = "TK_COMMA",
[TK_COMMENT] = "TK_COMMENT",
[TK_CONTINUE] = "TK_CONTINUE",
[TK_DEF] = "TK_DEF",
[TK_DEL] = "TK_DEL",
[TK_DIVDIV] = "TK_DIVDIV",
[TK_DIVDIV_EQ] = "TK_DIVDIV_EQ",
[TK_DIV_EQ] = "TK_DIV_EQ",
[TK_DOT] = "TK_DOT",
[TK_DQ] = "TK_DQ",
[TK_ELIF] = "TK_ELIF",
[TK_ELSE] = "TK_ELSE",
[TK_EQ] = "TK_EQ",
[TK_EQEQ] = "TK_EQEQ",
[TK_ESC_BACKSLASH] = "TK_ESC_BACKSLASH",
[TK_EXCEPT] = "TK_EXCEPT",
[TK_FINALLY] = "TK_FINALLY",
[TK_FOR] = "TK_FOR",
[TK_FROM] = "TK_FROM",
[TK_GE] = "TK_GE",
[TK_GLOBAL] = "TK_GLOBAL",
[TK_ID] = "TK_ID",
[TK_IF] = "TK_IF",
[TK_IMPORT] = "TK_IMPORT",
[TK_IN] = "TK_IN",
[TK_IS] = "TK_IS",
[TK_LAMBDA] = "TK_LAMBDA",
[TK_LANGLE] = "TK_LANGLE",
[TK_LBRACE] = "TK_LBRACE",
[TK_LBRACK] = "TK_LBRACK",
[TK_LE] = "TK_LE",
[TK_LLANGLE] = "TK_LLANGLE",
[TK_LLANGLE_EQ] = "TK_LLANGLE_EQ",
[TK_LOAD] = "TK_LOAD",
[TK_LPAREN] = "TK_LPAREN",
[TK_MINUS] = "TK_MINUS",
[TK_MINUS_EQ] = "TK_MINUS_EQ",
[TK_NONLOCAL] = "TK_NONLOCAL",
[TK_NOT] = "TK_NOT",
[TK_OR] = "TK_OR",
[TK_PASS] = "TK_PASS",
[TK_PCT] = "TK_PCT",
[TK_PCT_EQ] = "TK_PCT_EQ",
[TK_PLUS] = "TK_PLUS",
[TK_PLUS_EQ] = "TK_PLUS_EQ",
[TK_RAISE] = "TK_RAISE",
[TK_RANGLE] = "TK_RANGLE",
[TK_RBDQ] = "TK_RBDQ",
[TK_RBRACE] = "TK_RBRACE",
[TK_RBRACK] = "TK_RBRACK",
[TK_RBSQ] = "TK_RBSQ",
[TK_RDQ] = "TK_RDQ",
[TK_RETURN] = "TK_RETURN",
[TK_RPAREN] = "TK_RPAREN",
[TK_RRANGLE] = "TK_RRANGLE",
[TK_RRANGLE_EQ] = "TK_RRANGLE_EQ",
[TK_RSQ] = "TK_RSQ",
[TK_SEMI] = "TK_SEMI",
[TK_SLASH] = "TK_SLASH",
[TK_SQ] = "TK_SQ",
[TK_SQ3] = "TK_SQ3",
[TK_STAR] = "TK_STAR",
[TK_STARSTAR] = "TK_STARSTAR",
[TK_STAR_EQ] = "TK_STAR_EQ",
[TK_DQSTRING] = "TK_DQSTRING",
[TK_TILDE] = "TK_TILDE",
[TK_TRY] = "TK_TRY",
[TK_VBAR] = "TK_VBAR",
[TK_VBAR_EQ] = "TK_VBAR_EQ",
[TK_WHILE] = "TK_WHILE",
[TK_WITH] = "TK_WITH",
[TK_YIELD] = "TK_YIELD",
[TK_NUMBER] = "TK_NUMBER",
[TK_NEWLINE] = "TK_NEWLINE",
};

void dump_ast(struct obazl_buildfile_s *ast)
{
    log_debug("dump_ast");
    log_debug("fname: %s", ast->fname);

    struct node_s *p;
    for(p=(struct node_s*)utarray_front(ast->nodelist);
        p!=NULL;
        p=(struct node_s*)utarray_next(ast->nodelist, p)) {
        log_debug("node type: %d", p->type);
    }
}
