(if (or *mibl-debug-s7-loads* *mibl-debug-s7*)
    (format #t "loading starlark.scm\n"))

(define *select-protases* '())

(load "libmibl.scm")
;; (load "dune.scm")

(load "starlark/parsers.scm")
(load "starlark/singletons.scm")
(load "starlark/cc.scm")
(load "starlark/deps.scm")
(load "starlark/emit.scm")
(load "starlark/headers.scm")
(load "starlark/executables_starlark.scm")
(load "starlark/aggregates.scm")
(load "starlark/conditionals.scm")
(load "starlark/opam.scm")
(load "starlark/prologues.scm")
(load "starlark/ppx_starlark.scm")
(load "starlark/tests.scm")
(load "starlark/genrule.scm")
(load "starlark/profiles.scm")
(load "starlark/rules_starlark.scm")
(load "starlark/shell.scm")
(load "starlark/tools.scm")
(load "starlark/attributes.scm")
(load "starlark/filegroups.scm")
(load "starlark/starlark.scm")

(if *mibl-debug-s7*
    (format #t "loaded starlark.scm\n"))
